default_provider = "age"

[providers.age]
type = "age"
recipients = ["age1nlqfv0ptcfs7ssuuq8c06nprslcvwg9qpt6kf0ex20jhnknjmsqsrqf96k"]

[secrets]
NPM_TOKEN = { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWDNZeXgydnZEUnlsVEdhWGd2T2JvZ0pvQmRXVzk4RVh6Q0ZrVUhJNlRjClFpQjBXcC95TlhlOHo3UWF4SFR6SDYvaXlvcmhDVzhBWFlaczVhcitUdXcKLT4gYy1ncmVhc2UgJk1zIChCXi1bCkt6L1grUjNCNUFoRmlFWUd3L0lCVUxEY1ZVMHY3ZUc4RjBTcW5EcSsyR3hqY2pVUFFzQ0RYN0FFUDExQXU1K0YKMVEKLS0tIEpyRFZTczZCL2RnK3lQamtLMElFcXkrQWRvZEJxK3AxR3lRUUhIcVFsM1EKAyVNQvTHNd/v0I9MpeLUcS1kBzbzxFcmdgV8mTbHkbBc8Ko/SIcMAmDc8LlntAA2oW19KhQlP8Y+xObubafd+P4pZsOSmub/" }
