[tools]
# Stack
node = { version = "lts", postinstall = "node -v > .nvmrc" }
pnpm = "latest"

# Utils
opencode = "latest"

[settings]
lockfile = true # Enable lock file
experimental = true # Extra features
idiomatic_version_file_enable_tools = [] # Ignore .nvmrc and others
