
# Task templates ###############################################################


# Test =========================================================================

# test ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[task_templates."pkg/test"]
run = "pnpm exec vitest run"

# test:watch ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[task_templates."pkg/test:watch"]
run = "pnpm exec vitest"


# Types ========================================================================

# types
[task_templates."pkg/types"]
run = "pnpm exec tsc --build"

# types:watch
[task_templates."pkg/types:watch"]
run = "pnpm exec tsc --build --watch"


# Format =======================================================================

# format ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[task_templates."pkg/format"]
run = "pnpm exec oxfmt"

# format:check ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[task_templates."pkg/format:check"]
run = "pnpm exec oxfmt --check"


# Lint =========================================================================

# lint ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[task_templates."pkg/lint"]
run = "pnpm exec oxlint"


# Build ========================================================================

# build ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[task_templates."pkg/build"]
run = "pnpm exec jsd build"


# Publish ======================================================================

# publish ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[task_templates."pkg/publish"]
depends = ["build"]
usage = '''
flag "--next" help="Tag package as next"
'''
run = '''
#!/usr/bin/env bash

set -euo pipefail

echo
echo "🚧 Publishing package to npm"
echo

NPM_TOKEN=$(fnox get NPM_TOKEN)
if [ -z "$NPM_TOKEN" ]; then
  echo "🔴 NPM_TOKEN env var is not set! Do you have fnox access configured?"
  exit 1
fi

PNPM_CONFIG__AUTH="{\"https://registry.npmjs.org\":{\"@\":{\"authToken\":\"$NPM_TOKEN\"}}}"

build_args=(--dir dist --access public --no-git-checks)

if [ "${usage_next:-false}" = "true" ]; then
  echo "🔵 Tag: next"
  build_args+=(--next)
else
  echo "🔵 Tag: latest"
fi

echo
echo "🌀 Running \`pnpm publish\`:"
echo "........................................................................."
PNPM_CONFIG__AUTH=$PNPM_CONFIG__AUTH pnpm publish "${build_args[@]}"
echo "........................................................................."
echo "🟢 Publish completed"

echo
echo "🎉 Successfully published package to npm"
echo
'''

# publish:next ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[task_templates."pkg/publish:next"]
run = [{ task = "publish", args = ["--next"] }]
