# Tasks ########################################################################

# Build ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# build
[tasks."build"]
run = "node ./src/bin.ts build"
