[tasks.test]
run = "pnpm exec vitest run"

[tasks."test:watch"]
run = "pnpm exec vitest"

[tasks.types]
run = "pnpm exec tsc --build"

[tasks."types:watch"]
run = "pnpm exec tsc --build --watch"

[tasks.build]
run = "pnpm exec jsd build"

[tasks.publish]
depends = ["build"]
run = "pnpm --dir dist publish --access public"

[tasks."publish:next"]
depends = ["build"]
run = "pnpm --dir dist publish --access public --tag next"
