# Settings #####################################################################

monorepo_root = true

[monorepo]
config_roots = ["pkgs/*", "pkgs/*/src/*/*.pkg/"]

[settings]
lockfile = true # Enable lock file


# Env ##########################################################################

[env]


# Tools ########################################################################

[tools]


# Stack ========================================================================

# Node.js
node = "lts"
pnpm = "latest"


# Toolset ======================================================================

fnox = "latest" # Secrets manager


# Tasks ########################################################################


# Test =========================================================================

# test ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[tasks.test]
extends = "pkg/test"

# test:watch ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[tasks."test:watch"]
extends = "pkg/test:watch"


# Types ========================================================================


# types ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[tasks.types]
extends = "pkg/types"

# types:watch ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[tasks."types:watch"]
extends = "pkg/types:watch"


# Format =======================================================================

# format ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[tasks.format]
extends = "pkg/format"

# format:check ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[tasks."format:check"]
extends = "pkg/format:check"


# Lint =========================================================================

# lint ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[tasks."lint"]
extends = "pkg/lint"


# Task templates ###############################################################


# Benchmark ====================================================================

# bench ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[task_templates."pkg/bench"]
run = "cd _bench.pkg && mise bench"
